name: Cloud-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest-m

    steps:
    - uses: actions/checkout@v4
    - name: Cloud-CI cozyboard_2023
      run: |
        rustup target add thumbv7em-none-eabi
        cargo build --release
        (cd flash-algo && cargo build --release --target thumbv7em-none-eabi)
        cargo test
        cargo fmt --all -- --check
        cargo clippy
        cargo machete
