name: Cloud-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cloud-CI fuota_fragmentation
      run: |
        git lfs pull
        rustup target add thumbv7em-none-eabi
        cargo install cargo-machete
        cargo build --release --no-default-features
        cargo build --release --no-default-features --features force-full-r
        cargo build --release --no-default-features --features matrixreconstructor
        ./build_all.sh
